
CREATE TABLE IF NOT EXISTS SONGTABLE (id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,title VARCHAR(50),artist VARCHAR(50) NOT NULL,label VARCHAR(50),released INTEGER);


insert into SONGTABLE(title, artist, label, released) values ('MacArthur Park', 'Richard Harris', 'Dunhill Records', 1968);
insert into SONGTABLE(title, artist, label, released) values ('Afternoon Delight', 'Starland Vocal Band	', 'Windsong', 1976);
insert into SONGTABLE(title, artist, label, released) values ('Muskrat Love', 'Captain and Tennille', 'A&M', 1976);
