CREATE TABLE IF NOT EXISTS USERTABLE (userid VARCHAR(50) NOT NULL PRIMARY KEY,password VARCHAR(50),firstName VARCHAR(50) NOT NULL,lastName VARCHAR(50));

insert into USERTABLE(userid, password, firstName, lastName) values ('maxime', 'pass1234', 'Maxime', 'Muster');
insert into USERTABLE(userid, password, firstName, lastName) values ('jane', 'pass1234', 'Jane', 'Doe');

CREATE TABLE IF NOT EXISTS SONG (id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,title VARCHAR(50) NOT NULL,artist VARCHAR(50) NOT NULL,label VARCHAR(50),released VARCHAR(50));
insert into SONG(title, artist, label, released) values ('MacArthur Park', 'Richard Harris', 'Dunhill Records', '1968');
insert into SONG(title, artist, label, released) values ('Afternoon Delight', 'Starland Vocal Band', 'Windsong', 1976);
insert into SONG(title, artist, label, released) values ('Muskrat Love', 'Captain and Tennille', 'A&M', 1976);







